FROM golang:1.13-alpine

RUN apk update \
    && apk upgrade \
    && apk add git \
    && go get golang.org/x/crypto/md4 \
    && go get golang.org/x/net/context \
    && go get golang.org/x/crypto/acme/autocert
RUN apk del git
