FROM golang:1.13

RUN apt-get update \
    && apt-get install -y --no-install-recommends apt-utils \
    && apt-get install -y git \
    && apt-get install -y wkhtmltopdf \
    && go get golang.org/x/crypto/md4 \
    && go get golang.org/x/net/context \
    && go get golang.org/x/crypto/acme/autocert

